services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - 5432:5432

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
        
  migrations:
    build: ./backend
    restart: on-failure
    command: >
      python manage.py migrate
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - 9000:80
    depends_on:
      - backend
      - centrifugo
      - frontend

  frontend:
    build: ./frontend
    expose:
      - 80
    depends_on:
      - backend

  centrifugo:
    image: centrifugo/centrifugo:v6
    restart: unless-stopped
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c config.json
    environment:
      - CENTRIFUGO_HTTP_API_KEY=${CENTRIFUGO_API_KEY}
      - CENTRIFUGO_CLIENT_TOKEN_HMAC_SECRET_KEY=${CENTRIFUGO_TOKEN_SECRET}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:${REDIS_VERSION:-7}-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: