services:
  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "grandchat" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=grandchat
      - POSTGRES_PASSWORD=grandchat
      - POSTGRES_DB=grandchat
    expose:
      - 5432
    ports:
      - 5432:5432

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
        
  migrations:
    build: ./backend
    restart: on-failure
    command: >
      python manage.py migrate
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - 9000:80
    depends_on:
      - backend
      - centrifugo
      - frontend

  frontend:
    stdin_open: true
    build: ./frontend
    expose:
      - 5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  centrifugo:
    image: centrifugo/centrifugo:v6
    restart: unless-stopped
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c config.json
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:${REDIS_VERSION:-7}-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10